name: Build All MRS

on:
  workflow_dispatch:
#  schedule:
  #  - cron: '0 2 * * *'  # 每天自动构建

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download and install mihomo
        run: |
          mkdir -p ./tools/
          wget https://github.com/DustinWin/proxy-tools/releases/download/mihomo/mihomo-meta-linux-amd64.tar.gz -O - | tar -zxf - -C ./tools/
          mv -f ./tools/CrashCore ./tools/mihomo
          chmod +x ./tools/mihomo

      - name: Download and convert list files to .mrs
        run: |
          mkdir -p ./mihomo-ruleset

          declare -A urls
          urls["ChinaMedia"]="https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
          urls["GlobalMedia"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list"
          urls["Telegram"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"
          urls["YouTube"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list"
          urls["TikTok"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list"
          urls["Netflix"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list"
          urls["OpenAI"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list"
          urls["Twitter"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list"
          urls["Game"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list"
          urls["Apple"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list"
          urls["SystemOTA"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SystemOTA/SystemOTA.list"
          urls["Jejz_Cn"]="https://raw.githubusercontent.com/Jejz168/Clash/main/List/Jejz_Cn.list"
          urls["Jejz_Un"]="https://raw.githubusercontent.com/Jejz168/Clash/main/List/Jejz_Un.list"
          urls["Microsoft"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list"
          urls["PrivateTracker"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list"
          urls["ChinaNoMedia"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaNoMedia/ChinaNoMedia.list"
          urls["Proxy"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list"
          urls["ChinaIPs"]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs.list"

          input_dir="./mihomo-ruleset"
          convert_tool="./tools/mihomo"

          # 1. 下载所有 .list 文件
          for name in "${!urls[@]}"; do
            echo "Downloading and converting $name"
            curl -sSL "${urls[$name]}" -o "$input_dir/$name.list"
          done

          # 2. 清洗所有 .list 文件
          for file in "$input_dir"/*.list; do
            echo "Cleaning and merging $file"
            base_name="$(basename "$file" .list)"
            tmp_domain="${input_dir}/${base_name}_domain.list"
            tmp_ip="${input_dir}/${base_name}_ip.list"
            tmp_merged="${file}.merged.tmp"

            # 1. 提取并清洗域名类规则
            grep -E '^(DOMAIN|DOMAIN-SUFFIX|DOMAIN-KEYWORD),' "$file" | sed -E \
              -e 's/^DOMAIN,//' \
              -e 's/^DOMAIN-SUFFIX,/+\./' \
              -e 's/^DOMAIN-KEYWORD,//' \
              -e 's/,no-resolve$//' > "$tmp_domain"

            # 2. 提取并清洗 IP 类规则
            grep -E '^(IP-CIDR|IP-CIDR6),' "$file" | sed -E \
              -e 's/^IP-CIDR,//' \
              -e 's/^IP-CIDR6,//' \
              -e 's/,no-resolve$//' > "$tmp_ip"

            # 3. 合并成最终结果（用原 list 文件名）
            cat "$tmp_domain" "$tmp_ip" > "$tmp_merged"

            # 4. 覆盖回原文件
            mv "$tmp_merged" "$file"

          done

          # 3. 转换为 .mrs
          for file in "$input_dir"/*.list; do
            base_name="$(basename "$file" .list)"
            domain_list="${input_dir}/${base_name}_domain.list"
            ip_list="${input_dir}/${base_name}_ip.list"
            if [ -s "$domain_list" ]; then
              $convert_tool convert-ruleset domain text "$domain_list" "$input_dir/${base_name}_domain.mrs"
            else
              echo "Warning: $file is empty after cleaning, skipping .mrs"
            fi

            if [ -s "$ip_list" ]; then
              $convert_tool convert-ruleset ipcidr text "$ip_list" "$input_dir/${base_name}_ip.mrs"
            else
              echo "Warning: $file is empty after cleaning, skipping .mrs"
            fi
          done

           # 清理所有 _domain.list 和 _ip.list 中间文件
           rm -f "$input_dir"/*_domain.list "$input_dir"/*_ip.list

          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Upload .mrs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: mihomo-ruleset
          tag_name: mihomo-ruleset
          files: ./mihomo-ruleset/*
          body: |
            [mihomo](https://github.com/MetaCubeX/mihomo) rule-set 规则集文件  
            规则集文件更新于 ${{ env.update_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
